package normalize

import (
	"strings"
	"testing"
)

// Every wrapper shape below is a record observed on disk or in a hook payload
// (research r1 2.7/2.8, r5 D, r6 F4, evidence/probes.sql M1). The table is the
// contract: a shape that is not here is not a shape the product knows.
func TestClassifyUserWrapperForms(t *testing.T) {
	const caveat = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"
	const taskNote = "<task-notification>\n<task-id>a34dfc20a6d34c429</task-id>\n<tool-use-id>toolu_013g59jdkJbLDqHpDss5avN1</tool-use-id>\n<output-file>/tmp/tasks/a34dfc20a6d34c429.output</output-file>\n<status>completed</status>\n<summary>Agent \"sub-pong\" finished</summary>\n</task-notification>"

	cases := []struct {
		name    string
		text    string
		raw     string
		agent   bool
		first   bool
		want    Kind
		text2   string // expected Message.Text when it matters
		command string
		args    string
		subkind string
	}{
		// Slash commands: both tag orders, and the hook path's raw line.
		{name: "command-name first (built-in)", text: "<command-name>/effort</command-name>\n            <command-message>effort</command-message>\n            <command-args></command-args>",
			want: KindSlashCommand, command: "/effort", args: "", text2: "/effort", subkind: "effort"},
		{name: "command-message first (skill)", text: "<command-message>platform-engineer:platform-engineer</command-message>\n<command-name>/platform-engineer:platform-engineer</command-name>\n<command-args>Git fetch latest main before you do any research.</command-args>",
			want: KindSlashCommand, command: "/platform-engineer:platform-engineer", args: "Git fetch latest main before you do any research.", text2: "/platform-engineer:platform-engineer Git fetch latest main before you do any research."},
		{name: "hook path raw command", text: "/git --autonomous", want: KindSlashCommand, command: "/git", args: "--autonomous", text2: "/git --autonomous"},
		{name: "hook path bare command", text: "/standup", want: KindSlashCommand, command: "/standup", text2: "/standup"},
		{name: "hook path namespaced command", text: "/coderabbit:autofix", want: KindSlashCommand, command: "/coderabbit:autofix"},

		// Local commands and their output.
		{name: "caveat isMeta", text: caveat, raw: `{"type":"user","isMeta":true,"promptId":"dfa88d04"}`, want: KindCaveat},
		{name: "caveat without raw", text: caveat, want: KindCaveat},
		{name: "local command stdout", text: "<local-command-stdout>Set effort level to ultracode (this session only): xhigh</local-command-stdout>", want: KindCommandOutput, subkind: "local_command_stdout"},
		{name: "bash passthrough input", text: "<bash-input>export FOO=bar</bash-input>", want: KindCommandOutput, subkind: "bash_input"},
		{name: "bash passthrough output", text: "<bash-stdout>(Bash completed with no output)</bash-stdout><bash-stderr></bash-stderr>", want: KindCommandOutput, subkind: "bash_stdout"},

		// Notifications and peers.
		{name: "task notification transcript", text: taskNote, raw: `{"type":"user","origin":{"kind":"task-notification"},"promptSource":"system"}`, want: KindTaskNotification, text2: `Agent "sub-pong" finished`, subkind: "completed"},
		{name: "task notification hook path", text: taskNote, want: KindTaskNotification, text2: `Agent "sub-pong" finished`},
		{name: "task notification by origin only", text: "Background task done.", raw: `{"origin":{"kind":"task-notification"},"promptSource":"system"}`, want: KindTaskNotification, subkind: "origin"},
		{name: "system reminder standalone", text: "<system-reminder>\nThe user named this session \"Closure\". This may indicate the session's focus or intent.\n</system-reminder>", raw: `{"isMeta":true}`, want: KindSystemReminder},
		{name: "system reminder trailing on a prompt", text: "fix the bug\n\n<system-reminder>\nCLAUDE.md was modified.\n</system-reminder>", want: KindHuman, text2: "fix the bug"},
		{name: "system reminder leading a prompt", text: "<system-reminder>Context</system-reminder>\nMy question", want: KindHuman, text2: "My question"},
		{name: "teammate message transcript form", text: "Another Claude session sent a message:\n<teammate-message teammate_id=\"setup-inventory\" color=\"blue\">\n{\"type\":\"idle_notification\",\"from\":\"setup-inventory\"}\n</teammate-message>", want: KindTeammateMessage, subkind: "setup-inventory"},
		{name: "teammate message hook form", text: "<teammate-message teammate_id=\"research\" summary=\"Research finished\">Findings here.</teammate-message>", want: KindTeammateMessage, subkind: "research"},
		{name: "teammate message by origin", text: "hello from a peer", raw: `{"isMeta":true,"origin":{"kind":"peer"},"promptSource":"system"}`, want: KindTeammateMessage},
		{name: "system notification", text: "[SYSTEM NOTIFICATION] Background task completed", want: KindSystemNotification, text2: "Background task completed"},
		{name: "interrupted", text: "[Request interrupted by user]", want: KindInterrupted},
		{name: "interrupted for tool use", text: "[Request interrupted by user for tool use]", want: KindInterrupted, subkind: "tool_use"},
		// Codex files an interruption as a turn_aborted wrapper (stored four
		// to six times per second in production, review-1 finding 9); a
		// person quoting the tag mid-sentence is still a person.
		{name: "codex turn aborted", text: "<turn_aborted> The user interrupted the previous turn on purpose. Any pending work should be considered cancelled.", want: KindInterrupted, subkind: "turn_aborted"},
		{name: "codex turn aborted bare", text: "<turn_aborted>", want: KindInterrupted, subkind: "turn_aborted"},
		{name: "turn aborted quoted mid-sentence", text: "why does codex emit <turn_aborted> when I press escape", want: KindHuman},
		{name: "ide opened file", text: "<ide_opened_file>The user opened the file /x/y.go in the IDE.</ide_opened_file>", want: KindIDEContext},
		{name: "ide selection", text: "<ide_selection>lines 3-9</ide_selection>", want: KindIDEContext},

		// Compaction: by flag, by the summary sentence, by the boundary text.
		{name: "compaction by flag", text: "Summary of earlier work.", raw: `{"isCompactSummary":true,"isVisibleInTranscriptOnly":true}`, want: KindCompactSummary},
		{name: "compaction by prefix on a fork copy", text: "This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion.", raw: `{"origin":{"kind":"human"},"promptSource":"typed"}`, want: KindCompactSummary},
		{name: "compaction by boundary text", text: "Conversation compacted", want: KindCompactSummary},

		// A reminder the harness cut off before its closing tag is still a
		// reminder; the cut-off text must never title a session.
		{name: "system reminder unterminated", text: "<system-reminder>\nCLAUDE.md was modified. The file is 400 lines long", want: KindSystemReminder, subkind: "unterminated"},
		{name: "system reminder bare tag", text: "<system-reminder>", want: KindSystemReminder, subkind: "unterminated"},
		// The command envelope with no name in it is the harness's output,
		// not a person's, and not a command either.
		{name: "empty command envelope", text: "<command-name></command-name>\n<command-message>x</command-message>\n<command-args></command-args>", want: KindHarnessInjected, subkind: "empty_command"},

		// Codex and harness-injected prefixes (probes.sql M1).
		{name: "codex internal context", text: `<codex_internal_context source="goal">goal text</codex_internal_context>`, want: KindEnvContext},
		{name: "codex environment context", text: "<environment_context>\n  <cwd>/x</cwd>\n  <shell>zsh</shell>\n</environment_context>", want: KindEnvContext},
		{name: "codex agent history", text: "The following is the Codex agent history for this thread.", want: KindEnvContext},
		{name: "in-app browser context", text: "<in-app-browser-context url=\"https://x\">page</in-app-browser-context>", want: KindEnvContext},
		{name: "recommended plugins", text: "<recommended_plugins>\n- foo\n</recommended_plugins>", want: KindHarnessInjected},
		{name: "AGENTS.md bare", text: "# AGENTS.md instructions for /home/x/repo\n\n...", want: KindHarnessInjected},
		{name: "AGENTS.md wrapped", text: "<user_instructions>\n# AGENTS.md\n</user_instructions>", want: KindHarnessInjected},
		{name: "heartbeat", text: "<heartbeat><automation_id>abc</automation_id></heartbeat>", want: KindHarnessInjected},
		{name: "skill body", text: "<skill>\n# Skill\n</skill>", want: KindHarnessInjected},
		{name: "system instruction (Conductor)", text: "<system_instruction>You are Conductor.</system_instruction>", want: KindHarnessInjected},
		{name: "permissions preamble", text: "<permissions instructions>allow all</permissions instructions>", want: KindHarnessInjected},
		{name: "legacy Warmup", text: "Warmup", want: KindHarnessInjected},
		{name: "isMeta plain", text: "some meta text", raw: `{"isMeta":true}`, want: KindHarnessInjected, subkind: "meta"},
		{name: "skill expansion is meta not a command", text: "<command-message>x</command-message>\n<command-name>/x</command-name>\n<skill-format>true</skill-format>\n# The skill body", raw: `{"isMeta":true,"turnCompanion":true}`, want: KindHarnessInjected, subkind: "skill"},
		{name: "auto-continuation", text: "continue", raw: `{"isMeta":true,"origin":{"kind":"auto-continuation"},"promptSource":"system"}`, want: KindHarnessInjected},
		{name: "promptSource system", text: "Resume from summary.", raw: `{"promptSource":"system"}`, want: KindHarnessInjected, subkind: "system"},

		// Subagent streams.
		{name: "subagent driving prompt", text: "Review the diff in server/store and report findings.", agent: true, first: true, want: KindSubagentTask},
		{name: "subagent later prompt is a notification or human by text", text: taskNote, agent: true, first: false, want: KindTaskNotification},
		{name: "subagent later plain prompt", text: "keep going", agent: true, first: false, want: KindHuman},
		{name: "subagent Warmup is injected not a task", text: "Warmup", agent: true, first: true, want: KindHarnessInjected},

		// Plain humans, including the sdk-submitted ones.
		{name: "typed", text: "ship the ingest service", raw: `{"origin":{"kind":"human"},"promptSource":"typed"}`, want: KindHuman, text2: "ship the ingest service"},
		{name: "sdk submitted", text: "Run the shell command `touch gantry-fixture.txt`, then reply with exactly the word done.", raw: `{"entrypoint":"sdk-cli","promptSource":"sdk"}`, want: KindHuman},
		{name: "no raw at all", text: "what does this do", want: KindHuman},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			var raw []byte
			if tc.raw != "" {
				raw = []byte(tc.raw)
			}
			got := ClassifyUser(tc.text, raw, tc.agent, tc.first)
			if got.Kind != tc.want {
				t.Fatalf("kind = %q, want %q (%+v)", got.Kind, tc.want, got)
			}
			if tc.text2 != "" && got.Text != tc.text2 {
				t.Errorf("text = %q, want %q", got.Text, tc.text2)
			}
			if tc.command != "" && got.Command != tc.command {
				t.Errorf("command = %q, want %q", got.Command, tc.command)
			}
			if tc.command != "" && got.Args != tc.args {
				t.Errorf("args = %q, want %q", got.Args, tc.args)
			}
			if tc.subkind != "" && got.Subkind != tc.subkind {
				t.Errorf("subkind = %q, want %q", got.Subkind, tc.subkind)
			}
		})
	}
}

// A person talking about a wrapper is still a person. These are the inputs the
// reader's old classifier preserved, plus the path-shaped and slash-shaped
// prose the command rule must not swallow.
func TestClassifyUserNegatives(t *testing.T) {
	for _, text := range []string{
		"Please explain <task-notification> notifications",
		"```xml\n<task-notification><task-id>a</task-id></task-notification>\n```",
		"<task-notification><task-id>a</task-id></task-notification>\nPlease retry this.",
		"<task-notification><task-id>a</task-id>",
		"<task-notification>This is my proposed element</task-notification>",
		"[SYSTEM NOTIFICATION is a prefix I want to discuss",
		"why does <system-reminder> keep appearing in my prompts",
		"<system-reminder> is the tag I want to grep for",
		"/usr/local/bin/loop-sessions is missing from PATH",
		"/ divide these numbers",
		"look at <command-name> handling in the parser",
		"Another Claude session sent a message: is a phrase I saw in the logs",
		"This session is about billing, continue from where we left off",
		"Conversation compacted; can we pick up the auth refactor?",
		"Warmup the cache before the demo",
	} {
		if got := ClassifyUser(text, nil, false, false); got.Kind != KindHuman {
			t.Errorf("%q classified as %s, want human", text, got.Kind)
		} else if got.Text != strings.TrimSpace(text) {
			t.Errorf("%q: text rewritten to %q", text, got.Text)
		}
	}
}

// Trailing reminder blocks are split off so the displayed text is what was
// typed; the blocks are kept, not dropped.
func TestClassifyUserSplitsAttachedReminders(t *testing.T) {
	got := ClassifyUser("fix the flaky test\n<system-reminder>\nA</system-reminder>\n<system-reminder>B</system-reminder>", nil, false, false)
	if got.Kind != KindHuman || got.Text != "fix the flaky test" {
		t.Fatalf("got %+v", got)
	}
	if len(got.Attached) != 2 {
		t.Fatalf("attached = %v, want both reminder blocks", got.Attached)
	}
	// The same record on the command path keeps its command.
	got = ClassifyUser("<command-name>/review</command-name>\n<command-message>review</command-message>\n<command-args>pr 12</command-args>\n<system-reminder>x</system-reminder>", nil, false, false)
	if got.Kind != KindSlashCommand || got.Command != "/review" || got.Args != "pr 12" || len(got.Attached) != 1 {
		t.Fatalf("got %+v", got)
	}
}

// A hook payload passed where a transcript record belongs must be ignored, not
// read: its keys are the hook's, and reading isMeta or origin off it would be
// reading fields that mean something else.
func TestClassifyUserIgnoresHookPayloads(t *testing.T) {
	hook := `{"hook_event_name":"UserPromptSubmit","session_id":"s","isMeta":true,"prompt":"hi"}`
	if got := ClassifyUser("hi", []byte(hook), false, false); got.Kind != KindHuman {
		t.Errorf("a hook payload changed the verdict to %s", got.Kind)
	}
	if got := ClassifyUser("hi", []byte("not json"), false, false); got.Kind != KindHuman {
		t.Errorf("unparseable raw changed the verdict to %s", got.Kind)
	}
}

func TestInternalTemplates(t *testing.T) {
	for text, want := range map[string]string{
		"You are generating a short conversation title for a Claude Code session.": "title_generator",
		"You label Claude Code work in two words.":                                 "statusline_labeler",
		"Reply with exactly: pong":                                                 "pong",
		"You are a Claude-Mem observer.":                                           "claude_mem",
		"Hello memory agent, summarise this.":                                      "claude_mem",
		"<system_instruction>Conductor</system_instruction>":                       "system_instruction",
		"<recommended_plugins>\n- a\n</recommended_plugins>":                       "recommended_plugins",
	} {
		got, ok := IsInternalTemplate(text)
		if !ok || got != want {
			t.Errorf("IsInternalTemplate(%q) = (%q, %v), want (%q, true)", text, got, ok, want)
		}
	}
	for _, text := range []string{
		"fix the bug",
		"Can you reply with exactly: pong so I can test the hook?",
		"",
	} {
		if _, ok := IsInternalTemplate(text); ok {
			t.Errorf("IsInternalTemplate(%q) matched", text)
		}
	}
}

// The store applies the template list inside SQL with the exported cutset,
// so what this function strips before comparing is exactly that cutset and
// nothing more: a template behind a newline is a template on both sides, and
// one behind a character outside the cutset is a person on both sides.
func TestInternalTemplateTrimsExactlyTheExportedCutset(t *testing.T) {
	const tpl = "You are generating a short conversation title for a Claude Code session."
	if _, ok := IsInternalTemplate("\n\t " + tpl); !ok {
		t.Error("a template behind cutset whitespace was not matched")
	}
	if _, ok := IsInternalTemplate("\u00a0" + tpl); ok {
		t.Error("a template behind a character outside the cutset matched; the SQL side would not")
	}
	for _, c := range TemplateCutset {
		if c != ' ' && c != '\t' && c != '\r' && c != '\n' {
			t.Errorf("cutset carries %q, which has no Postgres ltrim equivalent in the statement", c)
		}
	}
}

func TestTitle(t *testing.T) {
	if got := Title(Message{Kind: KindHuman, Text: "first line\nsecond line"}); got != "first line" {
		t.Errorf("Title = %q", got)
	}
	if got := Title(Message{Kind: KindSlashCommand, Command: "/git", Args: "--autonomous"}); got != "/git --autonomous" {
		t.Errorf("Title = %q", got)
	}
	if got := Title(Message{Kind: KindSlashCommand, Command: "/effort"}); got != "/effort" {
		t.Errorf("Title = %q", got)
	}
	// A two-byte rune, so a byte-indexed cut would split a character.
	long := strings.Repeat("\u00e9", 250)
	if got := Title(Message{Kind: KindHuman, Text: long}); len([]rune(got)) != TitleMax {
		t.Errorf("Title of a long line kept %d runes, want %d", len([]rune(got)), TitleMax)
	}
}

func TestAssistantAndHumanKinds(t *testing.T) {
	if ClassifyAssistant("I did the thing.", true) != KindAssistantText {
		t.Error("prose classified as usage-only")
	}
	if ClassifyAssistant("   ", true) != KindAssistantUsageOnly {
		t.Error("blank turn with usage classified as text")
	}
	for k, want := range map[Kind]bool{KindHuman: true, KindSlashCommand: true, KindCaveat: false, KindSubagentTask: false, KindTaskNotification: false} {
		if IsHumanKind(k) != want {
			t.Errorf("IsHumanKind(%s) = %v", k, !want)
		}
	}
}
